version: 2
jobs:
  test:
    docker:
      - image: circleci/node:10.16
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          paths:
            - ~/.cache/yarn
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - run: yarn lint
      - run: yarn test:ci

  build:
    docker:
      - image: circleci/node:10.16
    working_directory: ~/repo
    steps:
      - checkout
      - run: echo ${DOT_ENV} | base64 --decode > ~/repo/.env
      - run: yarn install
      - run: yarn build
      - run:
          name: deploy to Firebase Hosting
          command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN
      - run:
        name: merge master to develop
        command: |
          git config --global user.email hello@nagomu.me
          git config --global user.name Kaoru Wada
          git fetch origin master
          git fetch origin develop
          git checkout develop
          git merge master
          git push origin develop

workflows:
  version: 2
  deploy:
    jobs:
      - test
      - build:
          requires:
            - test
          filters:
            branches:
              only:
                - master
