import { WorkoutTemplate } from '~/store/workout';

const rest = {
  isCompleted: false,
  isRest: true,
  menu: 0,
  scheduledDate: undefined,
  title: '',
};

export const workoutTemplate: WorkoutTemplate[] = [
  {
    isCompleted: false,
    isRest: false,
    menu: 20,
    scheduledDate: undefined,
    title: 'Day 1',
  },
  {
    isCompleted: false,
    isRest: false,
    menu: 20,
    scheduledDate: undefined,
    title: 'Day 2',
  },
  {
    isCompleted: false,
    isRest: false,
    menu: 30,
    scheduledDate: undefined,
    title: 'Day 3',
  },
  {
    isCompleted: false,
    isRest: false,
    menu: 30,
    scheduledDate: undefined,
    title: 'Day 4',
  },
  {
    isCompleted: false,
    isRest: false,
    menu: 40,
    scheduledDate: undefined,
    title: 'Day 5',
  },
  rest,
  {
    isCompleted: false,
    isRest: false,
    menu: 45,
    scheduledDate: undefined,
    title: 'Day 7',
  },
  {
    isCompleted: false,
    isRest: false,
    menu: 45,
    scheduledDate: undefined,
    title: 'Day 8',
  },
  {
    isCompleted: false,
    isRest: false,
    menu: 60,
    scheduledDate: undefined,
    title: 'Day 9',
  },
  {
    isCompleted: false,
    isRest: false,
    menu: 60,
    scheduledDate: undefined,
    title: 'Day 10',
  },
  {
    isCompleted: false,
    isRest: false,
    menu: 60,
    scheduledDate: undefined,
    title: 'Day 11',
  },
  {
    isCompleted: false,
    isRest: false,
    menu: 90,
    scheduledDate: undefined,
    title: 'Day 12',
  },
  rest,
  {
    isCompleted: false,
    isRest: false,
    menu: 90,
    scheduledDate: undefined,
    title: 'Day 14',
  },
  {
    isCompleted: false,
    isRest: false,
    menu: 90,
    scheduledDate: undefined,
    title: 'Day 15',
  },
  {
    isCompleted: false,
    isRest: false,
    menu: 120,
    scheduledDate: undefined,
    title: 'Day 16',
  },
  {
    isCompleted: false,
    isRest: false,
    menu: 120,
    scheduledDate: undefined,
    title: 'Day 17',
  },
  {
    isCompleted: false,
    isRest: false,
    menu: 150,
    scheduledDate: undefined,
    title: 'Day 18',
  },
  rest,
  {
    isCompleted: false,
    isRest: false,
    menu: 150,
    scheduledDate: undefined,
    title: 'Day 20',
  },
  {
    isCompleted: false,
    isRest: false,
    menu: 150,
    scheduledDate: undefined,
    title: 'Day 21',
  },
  {
    isCompleted: false,
    isRest: false,
    menu: 180,
    scheduledDate: undefined,
    title: 'Day 22',
  },
  {
    isCompleted: false,
    isRest: false,
    menu: 180,
    scheduledDate: undefined,
    title: 'Day 23',
  },
  {
    isCompleted: false,
    isRest: false,
    menu: 210,
    scheduledDate: undefined,
    title: 'Day 24',
  },
  {
    isCompleted: false,
    isRest: false,
    menu: 210,
    scheduledDate: undefined,
    title: 'Day 25',
  },
  rest,
  {
    isCompleted: false,
    isRest: false,
    menu: 240,
    scheduledDate: undefined,
    title: 'Day 27',
  },
  {
    isCompleted: false,
    isRest: false,
    menu: 240,
    scheduledDate: undefined,
    title: 'Day 28',
  },
  {
    isCompleted: false,
    isRest: false,
    menu: 270,
    scheduledDate: undefined,
    title: 'Day 29',
  },
  {
    isCompleted: false,
    isRest: false,
    menu: 300,
    scheduledDate: undefined,
    title: 'Day 30',
  },
];
